### ISSUE TITLE
Parent for machines 

### ISSUE THREAD

**Issue by mverderau** [fablabbcn/fablabs#109]
What is "Parent" for machines? 

Thanks

<img width="362" alt="captura de pantalla 2016-11-11 a las 11 25 31" src="https://cloud.githubusercontent.com/assets/23378598/20212118/d7a13f56-a801-11e6-8027-f6126a1f2a9e.png">

**Comment by openp2pdesign** [comment]
As it is now, it is not clear for a user... is it documented somewhere @hiromipaw @johnrees?

**Comment by johnrees** [comment]
This should be represented as a dropdown/association field. i.e. `parent_id`, don't know why it's being displayed that way. In this case the 'parent' is machine#23.

It's been a few years since I've looked at these models and their associations but I think the reasoning  behind it was to link revisions of machines e.g. a makerbot 2's 'parent' would be the makerbot - as you see in the list on https://www.fablabs.io/machines/1-makerbot-industries-replicator-2

Going forward it'd be much better to model in a graph though if possible, as some of these relationships are not so binary and have many forks, e.g. the reprap project.

**Comment by openp2pdesign** [comment]
Many thanks @johnrees! Regarding to this, would it make sense a graph database? Or it would be too much work?

**Comment by hiromipaw** [comment]
I think a graph database at this point is a bit of a stretch... my 2c here.

**Comment by openp2pdesign** [comment]
Yes @hiromipaw, and of course it would not be just for the parents in machines, but for the interactions among labs. But for my research / analysis / visualization purposes, it's enough to import the data in a separated graph database regularly.

**Comment by openp2pdesign** [comment]
Getting back to the _Parent_ topic, is this just a UI/UX issue @johnrees @hiromipaw?
